<a href="https://colab.research.google.com/github/retuyu88/digitalentkominfo/blob/master/Copy_of_exercise_numpy_2d.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Exercise of Numpy Array

Question 1: Create a 4X2 integer array and Prints its attributes
a. The shape of an array.
b. Array dimensions.

In [30]:
import numpy as np
matrix = np.zeros((4,2),dtype=np.int)
print(matrix)
print('shape of array',matrix.shape)
print('dimension',matrix.ndim)

[[0 0]
 [0 0]
 [0 0]
 [0 0]]
shape of array (4, 2)
dimension 2


Question 2: Create a 5X2 integer array from a range between 100 to 200 such that the difference between each element is 10

In [32]:
import numpy as np
#matrix = np.zeros((5,2), dtype= np.int)
#matrix.arange(100,200,10)
sampleArray = np.arange(100, 200, 10)
sampleArray = sampleArray.reshape(5,2)
sampleArray

array([[100, 110],
       [120, 130],
       [140, 150],
       [160, 170],
       [180, 190]])

Question 3: Following is the provided numPy array. return array of items in the third column from all rows

In [18]:
sampleArray = np.array([[11 ,22, 33], [44, 55, 66], [77, 88, 99]])

print(sampleArray)
print(sampleArray[:,2])


[[11 22 33]
 [44 55 66]
 [77 88 99]]
[33 66 99]


Question 4: Following is the given numpy array return array of odd rows and even columns

In [0]:
sampleArray = np.array([[3 ,6, 9, 12], 
                        [15 ,18, 21, 24], 
                        [27 ,30, 33, 36], 
                        [39 ,42, 45, 48], 
                        [51 ,54, 57, 60]])

#print(sampleArray)
print(sampleArray[::2,1::2])

[[ 6 12]
 [30 36]
 [54 60]]


Question 5: Add the following two NumPy arrays and Modify a result array by calculating the square root of each element

In [27]:
arrayOne = np.array([[5, 6, 9], [21 ,18, 27]])
arrayTwo = np.array([[15 ,33, 24], [4 ,7, 1]])

arrayThree = arrayOne * arrayTwo
print(arrayThree)
arrayThree = arrayThree**2
print(arrayThree)
a = arrayThree.shape
type(arrayThree.shape)
a

[[ 75 198 216]
 [ 84 126  27]]
[[ 5625 39204 46656]
 [ 7056 15876   729]]


(2, 3)

In [19]:
75**2

5625